
[general]
import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[terminal.shell]
program = "/usr/bin/env"
args = ["zsh"]
# program = "/opt/homebrew/bin/zellij"

[window]
decorations = "None"
opacity = 0.85
option_as_alt = "Both"

[window.padding]
x = 0
y = 0

[font]
size = 12
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }

[env]
TERM = "xterm-256color"
MULTIPLEXER = "tmux"
PATH = "/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
