# /Users/sebastianuskh/.config/tmuxinator/vsplit.yml

name: <%= File.basename(Dir.pwd) %>
root: .
windows:
  - editor:
      layout: 7a44,273x62,0,0{162x62,0,0,18,110x62,163,0,20}
      panes:
        - vim
        -
